# Generated by Django 4.2.7 on 2023-11-20 08:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.UUIDField(default=uuid.UUID('139aeaef-6509-40c5-a074-4bedea6ca509'))),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type_movie', models.CharField(choices=[('Series', 'Series'), ('Film', 'Film')], max_length=10)),
                ('length', models.PositiveSmallIntegerField()),
                ('release_date', models.DateField()),
                ('movie_image', models.ImageField(upload_to='image_movie/%Y/%m/%d')),
                ('movie_poster', models.ImageField(upload_to='poster_movie/%Y/%m/%d')),
                ('movie_video', models.FileField(upload_to='video/%Y/%m/%d')),
                ('movie_views', models.PositiveIntegerField(default=0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie_genre', to='core.genre')),
            ],
        ),
    ]
