# Generated by Django 4.2.7 on 2023-11-20 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_movie_genre_alter_movie_movie_id_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.UUIDField(default=uuid.UUID('0bb10f7b-ac2e-4436-9555-521ba8080dc5')),
        ),
    ]
